-- SPDX-License-Identifier: AGPL-3.0-or-later
--
-- The project table, and the boundary every later migration refers to.
--
-- A self-hosted install holds exactly one row here for the life of the deployment. It exists
-- because the alternative is adding a tenant column to a finished schema later, which means
-- touching every table, every foreign key, every index, every query and every URL at once.
--
-- Identifiers are generated by the application, not by a database default. That keeps the
-- migrations free of vendor-specific UUID functions and means an entity has its identity before
-- it is written, which is what lets a caller build a graph of related rows in one transaction.

create table project (
    id          uuid         not null,
    slug        varchar(64)  not null,
    name        varchar(120) not null,
    created_at  timestamp with time zone not null,

    constraint pk_project primary key (id),
    constraint uq_project_slug unique (slug),
    -- Mirrors the pattern in io.ludus.domain.shared.Slug and the id pattern in the wave schema.
    -- The application checks first so the error message is useful; the constraint exists so a
    -- value that skipped the application cannot be stored at all.
    constraint ck_project_slug_format check (regexp_like(slug, '^[a-z0-9_]+$'))
);
